### PR TITLE
feat: :sparkles: add @ToObjectId() decorator

### PR DESCRIPTION
**Pull request by somnathPrasad**
Added a @ToObjectId() decorator which can be used in dto files to convert string objectId received to request to proper ObjectId

### CODE REVIEW

**Comment by vlbras** [comment]
Hi, @somnathPrasad  . Thank you for your attention to `nestjs-object-id` and proposed feature. It is now available from `v1.4.2`

**Comment by somnathPrasad** [comment]
Hey @vlbras  I am using this package on a project. This is the feature I needed. Thank a lot

**Comment by vlbras** [comment]
Hey @somnathPrasad, I released `v2.0.1`, were I fixed some bugs, removed `@ToObjectId()` and introduced `@ParseObjectId() `which also validates `Types.ObjectId`. Highly recommend you to update `nestjs-object-id` in your projects

**Comment by somnathPrasad** [comment]
Hey @vlbras thanks a lot man

**Pull request merged**
